## Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia

os:
  - linux
  - osx

julia:
  - 1.4
  - 1.5
  - nightly

branches:
  only:
  - master
  - develop

script: 
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia --project -e 'using Pkg; Pkg.add("PyCall"); Pkg.instantiate(); ENV["PYTHON"] = ""; Pkg.build(); using PyCall; pyimport_conda("scipy", "scipy")'
 - julia --project -e 'using PyCall; pyimport_conda("scipy", "scipy")' # retry
 - julia --project -e 'using Pkg; Pkg.test(; coverage=true)';

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("GeometricFlux")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

notifications:
  email: false

env:
  - JULIA_CUDA_SILENT=true DATADEPS_ALWAYS_ACCEPT=true

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - stage: Documentation
      julia: 1.5
      script: julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
